version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialbd
    ports:
      - "5433:5432"
    volumes:
      - socialdata:/var/lib/postgresql/data
#   kafka:
#     image: bitnami/kafka:latest
#     container_name: kafka
#     environment:
#       - KAFKA_BROKER_ID=1
#       - KAFKA_LISTENERS=PLAINTEXT://:9092
#       - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#       - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
#       - ALLOW_PLAINTEXT_LISTENER=yes
#       - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
#       - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
#       - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
#       - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
#     ports:
#       - "9093:9092"
#     volumes:
#       - kafka_data:/bitnami/kafka
volumes:
  socialdata:
#   kafka_data:
